### PR TITLE
Classifier removed from labeler

### PR DESCRIPTION
**Pull request by mazhurin**

### CODE REVIEW

**Comment by mazhurin** [comment]
The previous idea of labeling relied on the assumption that all the IPs active immediately before a massive attack are not malicious. We don't have much evidence to support this assumption.

**Comment by mhqz** [comment]
Hi @mazhurin, based on the description of the problem, and my still limited understanding of the system, the patch seems fine to me, thanks for sharing this :+1: 

From a general development perspective; I'd like to suggest (only if it adapts to the current workflow that you're following), to remove commented code as we can recover it from commits if needed.

I've also noticed that tests are failing from a while and I'd like to ask; are those UT something relevant to fix? If that's the case I could volunteer to fix them in the near future.

**Review by mhqz — APPROVED** [review]

**Comment by mazhurin** [comment]
Thanks, @mhqz . 
* commented code: absolutely. 
* tests: yes, they are failing. We have a lot of outdated tests. We need to remove the old ones and disable PR merge if tests are failing. If you have time to do that, sure, it would be nice.

**Comment by mhqz** [comment]
Thank you @mazhurin, I've created a separate issue for it

**Pull request merged**
